(ns translations.es (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def translations {
  "|" ""})

(swap! fulcro.i18n/*loaded-translations* assoc "es" translations)
